name: Spessu
options:
  bundleIdPrefix: com.spessu
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ARCHS: arm64
    ONLY_ACTIVE_ARCH: "NO"

targets:
  Spessu:
    type: application
    platform: macOS
    sources:
      - path: Spessu
        excludes:
          - "*.xcassets/AppIcon.appiconset/*.png"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.spessu.app
        PRODUCT_NAME: Spessu
        INFOPLIST_FILE: Spessu/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Spessu/Spessu.entitlements
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
    info:
      path: Spessu/Info.plist
      properties:
        CFBundleName: Spessu
        CFBundleDisplayName: Spessu
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        NSHighResolutionCapable: true
        NSPrincipalClass: NSApplication
    entitlements:
      path: Spessu/Spessu.entitlements
      properties:
        com.apple.security.app-sandbox: false
